TWEAK_NAME = SpringJumps
SpringJumps_OBJCC_FILES = SpringJumps.mm
SpringJumps_CFLAGS = -F$(SYSROOT)/System/Library/PrivateFrameworks -F$(SYSROOT)/System/Library/CoreServices
SpringJumps_FRAMEWORKS = UIKit QuartzCore CoreGraphics
SpringJumps_PRIVATE_FRAMEWORKS = GraphicsServices

include framework/makefiles/common.mk
include framework/makefiles/tweak.mk
